### ISSUE TITLE
fade() does not work

### ISSUE THREAD

**Issue by mtancoigne** [nusu/spectre.scss#1]
Hi !

First of all, thanks for your job !

I started using Spectre.scss for a VueJS project, and when the scss is being compiled, some backgrounds are set to `fade(<color>, <amount>)`, which is compiled as-is. The browser (Chrome) does not recognise it.

Shouldn't you use fade-in() instead ?

**Comment by nusu** [comment]
ohh looks like I forgot to replace fade as fade in, I'm going to merge now.

**Comment by nusu** [comment]
#2
